SAC:
  batch_size: 64
  buffer_size: 1000000
  layers: [64, 64]
  max_iters: 400
  save_dir: gripper_20211108
  step_size: 0.0003
  tensorboard_logs: null
  total_timesteps: 10000000 #150000
algorithm: sac
curriculum:
  extent: [0.01, 0.1]
  init_lambda: 0.0
  lift_dist: [0.015, 0.1]
  max_objects: [3, 5]
  min_objects: [1, 1]
  n_steps: 8
  robot_height: [0.15, 0.25]
  success_threshold: 0.7
  window_size: 1000
depth_observation: false
discount_factor: 0.99
full_observation: true
normalize: true
reward: {custom: true, delta_z_scale: 1000.0, grasp_reward: 100.0, shaped: true, terminal_reward: 10000.0,
  time_penalty: 200.0}
robot: {discrete: false, max_force: 100, max_translation: 0.03, max_yaw_rotation: 0.15,
  model_path: assets/gripper/wsg50_one_motor_gripper_new.sdf, num_actions_pad: 2,
  step_size: 0.01, yaw_step: 0.1}
scene: {data_set: random_urdfs, scene_type: OnTable}
sensor:
  camera_info: config/camera_info.yaml
  randomize: {focal_length: 4, optical_center: 2, rotation: 0.0349, translation: 0.002}
  transform: config/camera_info.yaml
  visualize: false
simplified: false
simulation: {gravity: false, real_time: false, time_horizon: 150, unit_time: false,
  visualize: false}
skip_empty_initial_state: true
time_horizon: 150
